sudo: required
services:
  - docker

before_install:
  - docker build -t skrill0/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true skrill0/react-test npm test

after_success:
  - docker build -t skrill0/multi-client ./client
  - docker build -t skrill0/multi-nginx ./nginx
  - docker build -t skrill0/multi-server ./server
  - docker build -t skrill0/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push skrill0/multi-client
  - docker push skrill0/multi-nginx
  - docker push skrill0/multi-server
  - docker push skrill0/multi-worker